/*
 */

export const allPhrases = {
  custom: {
    chapter1: {
      name: 'Random vocab',
      lesson1: [
        { foreign: 'largo', english: 'long', working_on: true },
        {
          foreign: 'Tenga cuidado.',
          english: 'Be careful. (formal) (to a male)',
          working_on: true,
        },
        { foreign: 'aquí', english: 'here', working_on: true },
        { foreign: 'tiempo', english: 'weather', working_on: true },
      ],
    },
    chapter2: {
      name: 'Days of the week',
      lesson1: [
        { foreign: 'lunes', english: 'Monday' },
        { foreign: 'martes', english: 'Tuesday' },
        { foreign: 'miércoles', english: 'Wednesday' },
        { foreign: 'jueves', english: 'Thursday' },
        { foreign: 'viernes', english: 'Friday' },
        { foreign: 'sábado', english: 'Saturday' },
        { foreign: 'domingo', english: 'Sunday' },
      ],
    },
  },
  unit1: {
    name: 'Introductions',
    chapter1: {
      name: 'Salutations and Small Talk',
      lesson1: [
        { foreign: 'Hola.', english: 'Hello.' },
        { foreign: 'Buenos días.', english: 'Good morning.' },
        { foreign: 'Buenas tardes.', english: 'Good afternoon.' },
        { foreign: 'Buenas noches.', english: 'Good evening. / Good night.' },
      ],
      lesson2: [
        { foreign: '¿Cómo está usted?', english: 'How are you? (formal)' },
        { foreign: 'cómo', english: 'how' },
        { foreign: 'estar', english: 'to be (temporary)' },
        { foreign: 'está', english: '(you) are (formal)' },
        { foreign: 'estás', english: '(you) are (informal)' },
        { foreign: 'usted', english: 'you (formal)' },
        { foreign: 'Hola, ¿cómo está usted?', english: 'Hello, how are you? (formal)' },
        { foreign: 'hoy', english: 'today' },
        { foreign: 'Hola, ¿cómo está usted hoy?', english: 'Hello, how are you today? (formal)' },
        { foreign: 'tú', english: 'you (informal)' },
        { foreign: '¿Cómo estás?', english: 'How are you? (informal)' },
        { foreign: 'ella', english: 'she' },
        { foreign: '¿Cómo está ella?', english: 'How is she?' },
        { foreign: 'él', english: 'he' },
        { foreign: '¿Cómo está él?', english: 'How is he?' },
      ],
      lesson3: [
        { foreign: 'Estoy bien.', english: 'I’m fine.' },
        { foreign: 'yo', english: 'I' },
        { foreign: 'estoy', english: '(I) am (temporary)' },
        { foreign: 'bien', english: 'fine' },
        { foreign: 'Gracias.', english: 'Thank you.' },
        { foreign: 'y', english: 'and' },
        { foreign: '¿Y usted?', english: 'And you? (formal)' },
        { foreign: 'Estoy bien. ¿Y usted?', english: 'I’m fine. And you? (formal)' },
        { foreign: 'también', english: 'too' },
        { foreign: 'Estoy bien también.', english: 'I’m fine too.' },
        { foreign: 'De nada.', english: 'You’re welcome.' },
        { foreign: 'Está bien. or Ella está bien.', english: 'She is fine.' },
        { foreign: 'Está bien. or Él está bien.', english: 'He is fine.' },
        { foreign: 'cansado', english: 'tired', hard: true },
        { foreign: 'Está cansado.', english: 'He is tired.', hard: true },
        { foreign: 'Está cansada.', english: 'She is tired.', hard: true },
        {
          foreign: 'Usted está cansado.',
          english: 'You are tired. (formal) (to a male)',
          hard: true,
        },
      ],
      lesson4: [
        { foreign: '¡Qué día tan frío!', english: 'What a cold day!' },
        { foreign: 'día', english: 'day' },
        { foreign: 'qué', english: 'what' },
        { foreign: '¡Qué día!', english: 'What a day!' },
        { foreign: 'frío', english: 'cold' },
        { foreign: 'día frío', english: 'cold day' },
        { foreign: 'tan', english: 'so (as in “so hot”)' },
        { foreign: 'tarde', english: 'afternoon' },
        { foreign: 'tarde fría', english: 'cold afternoon' },
        { foreign: 'lluvioso', english: 'rainy', hard: true },
        { foreign: 'tarde fría y lluviosa', english: 'cold and rainy afternoon', hard: true },
        {
          foreign: '¡Qué tarde tan fría y lluviosa!',
          english: 'What a cold and rainy afternoon!',
          hard: true,
        },
        { foreign: 'caluroso', english: 'hot', hard: true },
        { foreign: 'mañana', english: 'morning' },
        { foreign: 'la mañana calurosa', english: 'the hot morning', hard: true },
        { foreign: 'La mañana está calurosa.', english: 'The morning is hot.', hard: true },
      ],
      lesson5: [
        { foreign: 'noche', english: 'night' },
        { foreign: '¡Qué noche tan calurosa!', english: 'What a hot night!' },
        { foreign: 'húmedo', english: 'humid' },
        { foreign: '¡Qué día tan húmedo!', english: 'What a humid day!' },
        { foreign: '¡Qué noche tan húmeda!', english: 'What a humid night!', working_on: true },
      ],
      lesson6: [
        {
          foreign: 'Que tenga un buen día.',
          english: 'Have a good day. (formal)',
          working_on: true,
          hard: true,
        },
        { foreign: 'un día', english: 'a day' },
        { foreign: 'bueno', english: 'good' },
        { foreign: 'un buen día', english: 'a good day' },
        {
          foreign: 'que',
          english:
            'that (the subordinate conjunction “that” as in, “I hope that you have a good day.”)',
        },
        { foreign: 'tener', english: 'to have' },
        { foreign: 'tenga', english: '(you) have [subjunctive] (formal)' },
        { foreign: '¡Que tenga un buen lunes!', english: 'Have a good Monday! (formal)' },
        { foreign: 'Igualmente.', english: 'Likewise.' },
        { foreign: 'ver', english: 'to see' },
        { foreign: 'Nos vemos.', english: 'See you.' },
        { foreign: 'el martes', english: 'on Tuesday' },
        { foreign: 'Nos vemos el martes.', english: 'See you on Tuesday.' },
      ],
    },
  },
};

/*
        { foreign: '', english: '' },
*/
