/*
 */

export const allPhrases = {
  custom: {
    chapter1: {
      name: 'Random vocab',
      lesson1: [
        { foreign: 'largo', english: 'long' },
        {
          foreign: 'Tenga cuidado.',
          english: 'Be careful. (formal) (to a male)',
          working_on: true,
        },
        { foreign: 'aquí', english: 'here' },
        { foreign: 'tiempo', english: 'weather (right now)' },
        {
          foreign: '¿Qué significa esa palabra?',
          english: 'What does that word mean?',
        },
        { foreign: 'Suena bien.', english: 'Sounds good.' },
        { foreign: 'sin embargo', english: 'however' },
        { foreign: 'ambos', english: 'both' },
        { foreign: 'entonces', english: 'so / then (like French alors)' },
        { foreign: 'estadounidense/es', english: 'American' },
        { foreign: 'hay', english: 'there is/there are' },
        {
          foreign: 'Estoy retirado/a / jubilado/a.',
          english: 'I’m retired.',
          working_on: true,
          hard: true,
        },
      ],
      lesson2: [
        { foreign: 'Buen día.', english: 'Good day.' },
        { foreign: 'caballero', english: 'gentleman', working_on: true },
        { foreign: 'señor', english: 'sir / Mr.' },
        { foreign: 'señora', english: 'ma’am / Mrs.' },
        { foreign: 'señorita', english: 'miss (addressing someone)' },
        { foreign: '¿Qué hay de nuevo?', english: 'What’s new?', working_on: true, hard: true },
        { foreign: '¿Qué pasa?', english: 'What’s up?' },
        { foreign: '¿Qué tal?', english: 'How’s it going?', working_on: true, hard: true },
        { foreign: 'muy', english: 'very' },
        { foreign: 'Muy bien.', english: 'Very well.' },
        { foreign: 'No muy bien.', english: 'Not very well.' },
        { foreign: 'Más o menos.', english: 'So-so.', working_on: true },
        { foreign: 'aburrido', english: 'bored' },
        { foreign: 'contento', english: 'happy' },
        { foreign: 'enojado', english: 'angry', working_on: true, hard: true },
        { foreign: 'estresado', english: 'stressed' },
        { foreign: 'nervioso', english: 'nervous' },
        { foreign: 'ocupado', english: 'busy' },
        { foreign: 'preocupado', english: 'worried' },
        { foreign: 'relajado', english: 'relaxed' },
        { foreign: '¿Y tú?', english: 'And you? (informal)' },
        {
          foreign: 'Encantado de conocerlo.',
          english: 'Pleased to meet you. (to a male)',
          working_on: true,
          hard: true,
        },
        { foreign: 'Igual.', english: 'Likewise. (short version)' },
        {
          foreign: 'Muy amable.',
          english: 'That’s very kind of you.',
          working_on: true,
          hard: true,
        },
        { foreign: 'Muchas gracias.', english: 'Thank you very much.' },
        { foreign: 'Con gusto.', english: 'You’re welcome. (With pleasure.)' },
        { foreign: '¡Chao!', english: 'Bye!' },
        { foreign: '¡Cuídate!', english: 'Take care! (informal)' },
        { foreign: '¡Cuídense!', english: 'Take care! (to a group)', working_on: true },
        { foreign: 'Nos vemos más tarde.', english: 'See you later.', working_on: true },
        {
          foreign: '¡Que te vaya bien!',
          english: 'I hope it goes well with you! (informal)',
          working_on: true,
          hard: true,
        },
        { foreign: 'Nos vemos pronto.', english: 'See you soon.', working_on: true },
        { foreign: 'Nos vemos mañana.', english: 'See you tomorrow.', working_on: true },
      ],
    },
    chapter2: {
      name: 'Days of the week',
      lesson1: [
        { foreign: 'lunes', english: 'Monday' },
        { foreign: 'martes', english: 'Tuesday' },
        { foreign: 'miércoles', english: 'Wednesday' },
        { foreign: 'jueves', english: 'Thursday' },
        { foreign: 'viernes', english: 'Friday' },
        { foreign: 'sábado', english: 'Saturday' },
        { foreign: 'domingo', english: 'Sunday' },
      ],
    },
    chapter3: {
      name: 'Weather',
      lesson1: [
        { foreign: 'Está frío.', english: 'It is chilly.' },
        { foreign: 'Está nublado.', english: 'It is cloudy.', working_on: true },
        { foreign: 'Está seco.', english: 'It is dry.' },
        { foreign: 'Está soleado.', english: 'It is sunny.' },
        { foreign: 'Está ventoso.', english: 'It is windy.' },
        { foreign: 'Hace frío.', english: 'It is chilly. (alternate)' },
        { foreign: 'Hace mucho frío.', english: 'It is freezing.' },
      ],
    },
    chapter4: {
      name: 'Guide to pronunciation',
      lesson1: [
        { foreign: 'la llave', english: 'the key' },
        { foreign: 'la yegua', english: 'the mare', working_on: true, hard: true },
        { foreign: 'la gallina', english: 'the hen' },
        { foreign: 'el yoga', english: 'the yoga' },
        { foreign: 'la lluvia', english: 'the rain' },
        { foreign: 'la galleta', english: 'the cookie' },
        { foreign: 'el yate', english: 'the yacht' },
      ],
      lesson2: [
        { foreign: 'la bañera', english: 'the bathtub' },
        { foreign: 'el vestido', english: 'the dress' },
        { foreign: 'el virus', english: 'the virus' },
        { foreign: 'la botella', english: 'the bottle' },
        { foreign: 'la bufanda', english: 'the scarf' },
        { foreign: 'la vaca', english: 'the cow' },
        { foreign: 'el/la bebé', english: 'the baby' },
      ],
      lesson3: [
        { foreign: 'la campana', english: 'the bell' },
        { foreign: 'el queso', english: 'the cheese' },
        { foreign: 'el kilo', english: 'the kilo' },
        { foreign: 'el conejo', english: 'the rabbit' },
        { foreign: 'la cuchara', english: 'the spoon' },
        { foreign: 'el kárate', english: 'the karate' },
        { foreign: 'la mantequilla', english: 'the butter' },
      ],
      lesson4: [
        { foreign: 'el zapato', english: 'the shoe' },
        { foreign: 'el cepillo', english: 'the brush', working_on: true, hard: true },
        { foreign: 'el semáforo', english: 'the traffic light' },
        { foreign: 'el zinc', english: 'the zinc' },
        { foreign: 'el cine', english: 'the cinema', hard: true },
        { foreign: 'la silla', english: 'the chair' },
        { foreign: 'el zorro', english: 'the fox' },
      ],
      lesson5: [
        { foreign: 'el jabón', english: 'the soap', hard: true },
        { foreign: 'el traje', english: 'the suit', working_on: true },
        { foreign: 'la gente', english: 'the people' },
        { foreign: 'el/la jirafa', english: 'the giraffe' },
        { foreign: 'el gimnasio', english: 'the gym' },
        { foreign: 'el ojo', english: 'the eye' },
        { foreign: 'el jugo', english: 'the juice' },
      ],
      lesson6: [
        { foreign: 'el garaje', english: 'the garage', hard: true },
        { foreign: 'el guepardo', english: 'the cheetah' },
        { foreign: 'la hamburguesa', english: 'the hamburger' },
        { foreign: 'la guitarra', english: 'the guitar' },
        { foreign: 'el águila', english: 'the eagle' },
        { foreign: 'la gorra', english: 'the cap' },
        { foreign: 'el gusano', english: 'the worm', working_on: true, hard: true },
      ],
      lesson7: [
        { foreign: 'el hacha', english: 'the axe' },
        { foreign: 'el helado', english: 'the ice cream' },
        { foreign: 'el hilo', english: 'the thread' },
        { foreign: 'el hueso', english: 'the bone', working_on: true, hard: true },
        { foreign: 'el hada', english: 'the fairy', hard: true, working_on: true },
        { foreign: 'la huella', english: 'the fingerprint / the footprint', working_on: true },
      ],
    },
    chapter5: {
      name: 'Los pronombres de sujeto',
      lesson1: [
        { foreign: 'yo', english: 'I' },
        { foreign: 'tú', english: 'you (informal singular)' },
        { foreign: 'él', english: 'he' },
        { foreign: 'ella', english: 'she' },
        { foreign: 'usted', english: 'you (formal singular)' },
        { foreign: 'nosotros / nosotras', english: 'we' },
        { foreign: 'vosotros / vosotras', english: 'you (informal plural in Spain)' },
        { foreign: 'ellos / ellas', english: 'they' },
        {
          foreign: 'ustedes',
          english: 'you (formal plural in Spain; both formal and informal plural in Latin America)',
        },
      ],
    },
    chapter6: {
      name: 'Verb conjugations',
      lesson1: [
        {
          foreign:
            'estar, present tense:' +
            '| (yo) estoy' +
            '| (tú) estás' +
            '| (él, ella, usted) está' +
            '| (nosotros / nosotras) estamos' +
            '| (vosotros / vosotras) estáis' +
            '| (ellos / ellas / ustedes) están',
          english: 'to be (position, location, action, condition, emotion):| I am, you are, etc.',
        },
        {
          foreign:
            'ser, present tense:' +
            '| (yo) soy' +
            '| (tú) eres' +
            '| (él, ella, usted) es' +
            '| (nosotros / nosotras) somos' +
            '| (vosotros / vosotras) sóis' +
            '| (ellos / ellas / ustedes) son',
          english:
            'to be (date/day, occupation, characteristic/class, time, origin, relation/religion):| I am, you are, etc.',
        },
      ],
    },
    chapter7: {
      name: 'Seasons',
      lesson1: [
        { foreign: 'estación(es)', english: 'season(s)', working_on: true },
        { foreign: 'invierno', english: 'winter', working_on: true, hard: true },
        { foreign: 'primavera', english: 'spring' },
        { foreign: 'verano', english: 'summer', working_on: true, hard: true },
        { foreign: 'otoño', english: 'fall / autumn' },
      ],
    },
  },
  genders: {
    chapter1: {
      name: 'Noun endings',
      showEnglish: false,
      lesson1: [
        {
          foreign: '-a',
          english: 'Feminine. Ejemplo: la gata (girl cat), la manzana (apple). Excepción: el día.',
        },
        {
          foreign: '-ad, -ed, -id, -ud',
          english:
            'Feminine. Ejemplo: la amistad (friendship), la pared (wall), la salud (health).',
        },
        { foreign: '-ción', english: 'Feminine. Ejemplo: la canción, la emoción, la situación.' },
        { foreign: '-eza', english: 'Feminine. Ejemplo: la tristeza (sadness), la cabeza (head).' },
        { foreign: '-is', english: 'Feminine. Ejemplo: la crisis, la tendonitis' },
        {
          foreign: '-z',
          english:
            'Feminine. Ejemplo: la cruz (cross), la nariz (nose). Excepción: el lápiz (pencil), el arroz (rice)',
        },
        {
          foreign: 'letras del abecedario',
          english: 'Feminine. Ejemplo: la a, la b, la c, ...',
        },
        { foreign: '-o', english: 'Masculine. Ejemplo: el banco. Excepción: la mano, la foto' },
        {
          foreign: '-ar, -er, -or',
          english:
            'Masculine. Ejemplo: el titular (owner), el computador, el taller (shop). Excepción: la flor (flower).',
        },
        {
          foreign: '-ma',
          english: 'Masculine. Ejemplo: el clima (weather), el problema, el sistema.',
        },
        {
          foreign: '-y',
          english: 'Masculine. Ejemplo: el rey (king), el buey (ox). Excepción: la ley (law).',
        },
        { foreign: '-x', english: 'Masculine. Ejemplo: el tórax (thorax).' },
        {
          foreign: '-al',
          english: 'Masculine. Ejemplo: el hospital, el terminal.',
          working_on: true,
        },
        {
          foreign: 'días de la semana',
          english: 'Masculine. El lunes, el martes, el miércoles, ...',
        },
        {
          foreign: 'puntos cardinales',
          english: 'Masculine. El norte, el sur, el esta, el oeste',
        },
        { foreign: 'mesos', english: 'Masculine. El enero, el febrero, el marzo, ...' },
        { foreign: 'números', english: 'Masculine. El uno, el dos, el tres, ...' },
      ],
    },
    chapter2: {
      name: 'Examples',
      lesson1: [
        { foreign: 'la gata', english: 'the girl cat' },
        { foreign: 'la manzana', english: 'the apple', working_on: true },
        { foreign: 'el día', english: 'the day' },
        { foreign: 'la amistad', english: 'the friendship' },
        { foreign: 'la pared', english: 'the wall' },
        { foreign: 'la salud', english: 'the health' },
        { foreign: 'la canción', english: 'the song' },
        { foreign: 'la emoción', english: 'the emotion' },
        { foreign: 'la situación', english: 'the situation' },
        { foreign: 'la crisis', english: 'the crisis' },
        { foreign: 'la tendonitis', english: 'the tendonitis' },
        { foreign: 'la cruz', english: 'the cross' },
        { foreign: 'la nariz', english: 'the nose' },
        { foreign: 'el lápiz', english: 'the pencil' },
        { foreign: 'el arroz', english: 'the rice' },
        { foreign: 'la a', english: 'the a' },
        { foreign: 'la b', english: 'the b' },
        { foreign: 'la c', english: 'the c' },
        { foreign: 'el banco', english: 'the bank' },
        { foreign: 'la mano', english: 'the hand' },
        { foreign: 'la foto', english: 'the photo', working_on: true, hard: true },
        { foreign: 'el titular', english: 'the owner' },
        { foreign: 'el computador/la computadora', english: 'the computer' },
        { foreign: 'el taller', english: 'the shop', working_on: true },
        { foreign: 'la flor', english: 'the flower' },
        { foreign: 'el clima', english: 'the weather (climate)', working_on: true, hard: true },
        { foreign: 'el problema', english: 'the problem' },
        { foreign: 'el sistema', english: 'the system' },
        { foreign: 'el rey', english: 'the king' },
        { foreign: 'el buey', english: 'the ox' },
        { foreign: 'la ley', english: 'the law' },
        { foreign: 'el tórax', english: 'the thorax' },
        { foreign: 'el hospital', english: 'the hospital' },
        { foreign: 'el terminal', english: 'the terminal' },
        { foreign: 'el lunes', english: 'the Monday (on Monday)' },
        { foreign: 'el miércoles', english: 'the Wednesday (on Wednesday)' },
        { foreign: 'el norte', english: 'the north' },
        { foreign: 'el sur', english: 'the south' },
        { foreign: 'el esta', english: 'the east', working_on: true, hard: true },
        { foreign: 'el oeste', english: 'the west', working_on: true, hard: true },
        { foreign: 'el enero', english: 'the January', working_on: true },
        { foreign: 'el febrero', english: 'the February' },
        { foreign: 'el marzo', english: 'the March' },
        { foreign: 'el uno', english: 'the one' },
        { foreign: 'el dos', english: 'the two' },
        { foreign: 'el tres', english: 'the three' },
        { foreign: 'la mesa', english: 'the table' },
        { foreign: 'el sofá', english: 'the sofa' },
        { foreign: 'el planeta', english: 'the planet', working_on: true, hard: true },
        { foreign: 'la calle', english: 'the street', hard: true },
        { foreign: 'el campo', english: 'the field', hard: true },
        { foreign: 'el/la policia', english: 'the police officer' },
        { foreign: 'el ordenador', english: 'the computer (like the French word)' },
        { foreign: 'la tristeza', english: 'the sadness' },
        { foreign: 'la cabeza', english: 'the head', working_on: true },
      ],
    },
  },
  unit1: {
    name: 'Introductions',
    chapter1: {
      name: 'Salutations and Small Talk',
      lesson1: [
        { foreign: 'Hola.', english: 'Hello.' },
        { foreign: 'Buenos días.', english: 'Good morning.' },
        { foreign: 'Buenas tardes.', english: 'Good afternoon.' },
        { foreign: 'Buenas noches.', english: 'Good evening. / Good night.' },
      ],
      lesson2: [
        { foreign: '¿Cómo está usted?', english: 'How are you? (formal)' },
        { foreign: 'cómo', english: 'how' },
        { foreign: 'estar', english: 'to be (temporary)' },
        { foreign: 'está', english: '(you) are (formal)' },
        { foreign: 'estás', english: '(you) are (informal)' },
        { foreign: 'Hola, ¿cómo está usted?', english: 'Hello, how are you? (formal)' },
        { foreign: 'hoy', english: 'today' },
        { foreign: 'Hola, ¿cómo está usted hoy?', english: 'Hello, how are you today? (formal)' },
        { foreign: '¿Cómo estás?', english: 'How are you? (informal)' },
        { foreign: '¿Cómo está ella?', english: 'How is she?' },
        { foreign: '¿Cómo está él?', english: 'How is he?' },
      ],
      lesson3: [
        { foreign: 'Estoy bien.', english: 'I’m fine.' },
        { foreign: 'estoy', english: '(I) am (temporary)' },
        { foreign: 'bien', english: 'fine' },
        { foreign: 'Gracias.', english: 'Thank you.' },
        { foreign: 'y', english: 'and' },
        { foreign: '¿Y usted?', english: 'And you? (formal)' },
        { foreign: 'Estoy bien. ¿Y usted?', english: 'I’m fine. And you? (formal)' },
        { foreign: 'también', english: 'too' },
        { foreign: 'Estoy bien también.', english: 'I’m fine too.' },
        { foreign: 'De nada.', english: 'You’re welcome.' },
        { foreign: 'Está bien. or Ella está bien.', english: 'She is fine.' },
        { foreign: 'Está bien. or Él está bien.', english: 'He is fine.' },
        { foreign: 'cansado', english: 'tired', hard: true },
        { foreign: 'Está cansado.', english: 'He is tired.', hard: true },
        { foreign: 'Está cansada.', english: 'She is tired.', hard: true },
        {
          foreign: 'Usted está cansado.',
          english: 'You are tired. (formal) (to a male)',
          hard: true,
        },
      ],
      lesson4: [
        { foreign: '¡Qué día tan frío!', english: 'What a cold day!' },
        { foreign: 'día', english: 'day' },
        { foreign: 'qué', english: 'what' },
        { foreign: '¡Qué día!', english: 'What a day!' },
        { foreign: 'frío', english: 'cold' },
        { foreign: 'día frío', english: 'cold day' },
        { foreign: 'tan', english: 'so (as in “so hot”)' },
        { foreign: 'tarde', english: 'afternoon' },
        { foreign: 'tarde fría', english: 'cold afternoon' },
        { foreign: 'lluvioso', english: 'rainy', hard: true },
        { foreign: 'tarde fría y lluviosa', english: 'cold and rainy afternoon' },
        {
          foreign: '¡Qué tarde tan fría y lluviosa!',
          english: 'What a cold and rainy afternoon!',
        },
        { foreign: 'caluroso', english: 'hot (weather)', hard: true },
        { foreign: 'mañana', english: 'morning' },
        { foreign: 'la mañana calurosa', english: 'the hot morning' },
        { foreign: 'La mañana está calurosa.', english: 'The morning is hot.' },
      ],
      lesson5: [
        { foreign: 'noche', english: 'night' },
        { foreign: '¡Qué noche tan calurosa!', english: 'What a hot night!' },
        { foreign: 'húmedo', english: 'humid' },
        { foreign: '¡Qué día tan húmedo!', english: 'What a humid day!' },
        { foreign: '¡Qué noche tan húmeda!', english: 'What a humid night!' },
      ],
      lesson6: [
        {
          foreign: 'Que tenga un buen día.',
          english: 'Have a good day. (formal)',
        },
        { foreign: 'un día', english: 'a day' },
        { foreign: 'bueno', english: 'good' },
        { foreign: 'un buen día', english: 'a good day', working_on: true },
        {
          foreign: 'que',
          english:
            'that (the subordinate conjunction “that” as in, “I hope that you have a good day.”)',
        },
        { foreign: 'tener', english: 'to have', working_on: true },
        { foreign: 'tenga', english: '(you) have [subjunctive] (formal)' },
        { foreign: '¡Que tenga un buen lunes!', english: 'Have a good Monday! (formal)' },
        { foreign: 'Igualmente.', english: 'Likewise.' },
        { foreign: 'ver', english: 'to see' },
        { foreign: 'Nos vemos.', english: 'See you.', working_on: true },
        { foreign: 'el martes', english: 'on Tuesday' },
        { foreign: 'Nos vemos el martes.', english: 'See you on Tuesday.', working_on: true },
      ],
    },
  },
};

/*
        { foreign: '', english: '' },
*/
